/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as ExamExamIdEssayRouteImport } from './routes/exam.$examId.essay'
import { Route as ExamExamIdMcqRouteImport } from './routes/exam.$examId.mcq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdEssayRoute = ExamExamIdEssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => ExamExamIdRoute,
} as any)
const ExamExamIdMcqRoute = ExamExamIdMcqRouteImport.update({
  id: '/mcq',
  path: '/mcq',
  getParentRoute: () => ExamExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/$examId/essay': typeof ExamExamIdEssayRoute
  '/exam/$examId/mcq': typeof ExamExamIdMcqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/$examId/essay': typeof ExamExamIdEssayRoute
  '/exam/$examId/mcq': typeof ExamExamIdMcqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRouteWithChildren
  '/exam/$examId/essay': typeof ExamExamIdEssayRoute
  '/exam/$examId/mcq': typeof ExamExamIdMcqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam/$examId' | '/exam/$examId/essay' | '/exam/$examId/mcq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$examId' | '/exam/$examId/essay' | '/exam/$examId/mcq'
  id:
    | '__root__'
    | '/'
    | '/exam/$examId'
    | '/exam/$examId/essay'
    | '/exam/$examId/mcq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamExamIdRoute: typeof ExamExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId/essay': {
      id: '/exam/$examId/essay'
      path: '/essay'
      fullPath: '/exam/$examId/essay'
      preLoaderRoute: typeof ExamExamIdEssayRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
    '/exam/$examId/mcq': {
      id: '/exam/$examId/mcq'
      path: '/mcq'
      fullPath: '/exam/$examId/mcq'
      preLoaderRoute: typeof ExamExamIdMcqRouteImport
      parentRoute: typeof ExamExamIdRoute
    }
  }
}

interface ExamExamIdRouteChildren {
  ExamExamIdEssayRoute: typeof ExamExamIdEssayRoute
  ExamExamIdMcqRoute: typeof ExamExamIdMcqRoute
}

const ExamExamIdRouteChildren: ExamExamIdRouteChildren = {
  ExamExamIdEssayRoute: ExamExamIdEssayRoute,
  ExamExamIdMcqRoute: ExamExamIdMcqRoute,
}

const ExamExamIdRouteWithChildren = ExamExamIdRoute._addFileChildren(
  ExamExamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamExamIdRoute: ExamExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
